language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
env:
  - DEP=[all]
  - DEP=[dev]
branches:
  only:
    - master
jobs:
  exclude:
  - python: "3.6"
    env: DEP=[dev]
  - python: "3.7"
    env: DEP=[dev]
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=$HOME/miniconda3/bin:$PATH
  - conda create --yes -n myenv python=$TRAVIS_PYTHON_VERSION
  - source activate myenv
  - pip install --upgrade pip
install:
  - pip install -e .$DEP
  - pip install pytest-cov coveralls
script:
  - black --check .
  - flake8 --config=.flake8 .
  - mypy cgp
  - isort --check-only cgp examples test
  - if [ "$DEP" = "[all]" -a $TRAVIS_PYTHON_VERSION = 3.8 ]; then
       pip install gym || exit 1;
       make -C docs/ html-examples-short || exit 1;
    fi
  - pytest --cov=cgp
after_success:
  - coveralls
deploy:
  - provider: script
    script: bash docs/deploy.sh
    on:
      python: 3.8
      condition: $DEP = "[all]"
    edge: true
  - provider: pages:git
    skip_cleanup: true
    verbose: true
    token: $GITHUB_TOKEN
    edge: true
    local_dir: ./docs/_build/html/
    keep_history: true
    on:
      python: 3.8
      condition: $DEP = "[all]"
