sudo: false
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
branches:
  only:
    - master
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=$HOME/miniconda3/bin:$PATH
  - conda create --yes -n myenv python=$TRAVIS_PYTHON_VERSION
  - source activate myenv
  - pip install --upgrade pip
install:
  - pip install -r requirements.txt
  - pip install pytest pytest-cov coveralls
  - pip install flake8 black
script:
  - cd test/ && pytest --cov && cd ../
  - black --check .
  - flake8 --config=.flake8 .
after_success:
  - coveralls

